# Generated by Django 3.2.6 on 2021-09-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acciones', '0004_alter_api_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='owner',
            new_name='User',
        ),
        migrations.AddField(
            model_name='api',
            name='SecretKey',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='api',
            name='valueBTC',
            field=models.FloatField(default=50000),
        ),
    ]
