# Generated by Django 3.2.6 on 2021-09-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acciones', '0005_auto_20210908_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='porcentaje',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='api',
            name='valorAbajo',
            field=models.FloatField(default=50000),
        ),
        migrations.AddField(
            model_name='api',
            name='valorArriba',
            field=models.FloatField(default=50000),
        ),
        migrations.AlterField(
            model_name='api',
            name='SecretKey',
            field=models.CharField(default='', max_length=500),
        ),
    ]
