# Generated by Django 3.2.6 on 2021-09-21 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acciones', '0006_auto_20210920_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialOrdenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=500)),
                ('resultado', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Api', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Historial', to='Acciones.api')),
            ],
        ),
    ]
