# Generated by Django 3.2.6 on 2021-10-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acciones', '0008_api_rangocompraventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='nuevoRangoArribaAbajo',
            field=models.FloatField(default=10000),
        ),
    ]
