# Generated by Django 3.2.6 on 2021-10-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acciones', '0009_api_nuevorangoarribaabajo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='nuevoRangoArribaAbajo',
            new_name='nuevoAbajoAbajo',
        ),
        migrations.AddField(
            model_name='api',
            name='nuevoAbajoArriba',
            field=models.FloatField(default=10000),
        ),
        migrations.AddField(
            model_name='api',
            name='nuevoArribaAbajo',
            field=models.FloatField(default=10000),
        ),
        migrations.AddField(
            model_name='api',
            name='nuevoArribaArriba',
            field=models.FloatField(default=10000),
        ),
    ]
