# Generated by Django 3.2.6 on 2021-10-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acciones', '0010_auto_20211005_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='nuevoAbajoAbajo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='api',
            name='nuevoAbajoArriba',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='api',
            name='nuevoArribaAbajo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='api',
            name='nuevoArribaArriba',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='api',
            name='porcentaje',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='api',
            name='rangoCompraVenta',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='api',
            name='valorAbajo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='api',
            name='valorArriba',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='api',
            name='valueBTC',
            field=models.FloatField(),
        ),
    ]
